# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AZS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AZS
  pod 'Alamofire', '~> 5.0.0-beta.5'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'SnapKit', '~> 5.0.0'
  pod 'Kingfisher', '~> 4.0.0'

  target 'AZSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AZSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
